### ISSUE TITLE
Streaming compatabiltiy with grpcio server

### ISSUE THREAD

**Issue by recro-lataille** [vmagamedov/grpclib#43] opened 2018-10-09 09:54 UTC
I am having issues with streaming data to grpcio server from grpclib client. this is a stream-unary connection. the issue is occurring when I send a large number of messages across the single stream connection (I am cutting a large file into small <4mb pieces and sending them from the client to server as bytes. when I use a grpclib server everything goes smoothly but when integrating with grpcio a number of messages send then the server hangs indefinably. This isn't exact but is essentially what I am doing (I probably have typos below). to replicate just create large bytesIO then cut it up and send it across in pieces. 

the call is very basic
async with stub.stream_parts.open() as stream:  
     for part in file_parts:
          await send_message(PartsStream(bytes=part['bytes']
     await stream.close()

**Comment by vadmbertr** [comment] 2019-01-24 17:07
I am experiencing a similar issue.


I have a server with two services A and B.
My client periodically fetches data from two different APIs asynchronously. One dataset is around 6kb and the other 60kb. Once a dataset is retrieve the client asynchronously sends the dataset (as bytes) to the stub A and to the stub B. The two stubs share the same Channel.

The code could be simplified like this:

```
async def collect(url):
    while True:
        await asyncio.gather(transmit(url), asyncio.sleep(60))

async def transmit(url):
    data = await get(url)
    await asyncio.gather(send_to_A(data), send_to_B(data))

async send_to_A(data):
    async with stubA.procedure.open() as stream:
        await stream.send_message(procedure_request(data=data), end=True)

async send_to_B(data):
    async with stubB.procedure.open() as stream:
        await stream.send_message(procedure_request(data=data), end=True)

asyncio.run(asyncio.gather(collect(url1), collect(url2)))
```


Often (not always) the first iteration goes fine. However during the second iteration one of the send_message coroutine of the larger dataset hangs forever. Iteration one the smaller dataset continues to work as expected.

I noticed that send_message hangs because the stream waits for the event __window_updated__ to be set. The size of the window changes but the h2 event RemoteSettingsChanged is not triggered, it is the WindowUpdated that is triggered with an stream_id = 0. But the lock is not released since _initial_window_size_changed is set to False (no RemoteSettingsChanged event).
To have my use case worked I need to get rid of the if self._initial_window_size_changed condition. This way the lock of my stream is set and the message sent.


Note that I don't know about h2 so I could be doing something conceptually completely wrong.

**Comment by vmagamedov** [comment] 2019-01-25 21:44
I've tried this example with grpcio on the server-side:
```python
while True:
    async with stub.StreamUnaryGreeting.open() as stream:
        for _ in range(1000):
            await stream.send_message(HelloRequest(name='*' * 65000))
        await stream.end()
        await stream.recv_message()
```
I've sent 400GB of data using single channel and everything went fine.

Do you have any thoughts about how I could reproduce this bug?

Conceptually I still can't imagine situation when connection's window was updated but stream's window wasn't.

**Comment by vadmbertr** [comment] 2019-01-26 06:10
I don't think I will be able to provide it before Monday. But to clarify, I am experiencing this using a true grpclib server, not grpcio.

**Comment by recro-lataille** [comment] 2019-01-26 16:45
Yes, the issue is interacting with a grpcio server via grpclib client or
vice versa.

**Comment by vmagamedov** [comment] 2019-01-28 11:12
Seems like I found valid explanation of streams stalling, and simplified `process_window_updated` method as @vadmbertr did. Issued `grpclib==0.2.2rc2` version with this fix, please try it.

It is possible that the other party manages unlimited stream-level windows and limited connection-level window. `grpclib` was expecting that the other party sends window update frame for every stream as soon as possible, but this is not always the case, and we also have to wait for connection-level window update frames all the time.

**Comment by vadmbertr** [comment] 2019-01-28 13:20
Yes the fix is working for me.
Do you still want a way to reproduce what was the bug? If not it is good to close this as far as I am concerned.

**Comment by vmagamedov** [comment] 2019-01-28 14:05
Ok.

**Closed by vmagamedov** 2019-01-28 14:05 UTC
Labels: bug
