### ISSUE TITLE
Stream response method memory leak

### ISSUE THREAD

**Issue by sky01230** [vmagamedov/grpclib#58] opened 2019-02-12 15:59 UTC
Hey!
I'm using stream response method with timeout.
```python
while True:
    try:
        channel = Channel(**HOST, loop=asyncio.get_event_loop(), ssl=my_ssl_context())
        stub = ServerStub(channel)
        async with stub.my_channel.open(timeout=1) as stream:
            await stream.send_message(sync_queue, end=True)
            async for message in stream:
                print(message)
    except Exception:
        logger.error('Error', exc_info=True)
```
If server does not send response in 1 second, i received an exception "Deadline exceed" and i try to connect again. This quickly ends all RAM memory.

**Comment by vmagamedov** [comment] 2019-02-12 23:49
Hi! Can you ensure that `channel.close()` is called before creating new channel? You also can create channel and stub only once, maybe there is no need to recreate it in every iteration, channel should try to reconnect every time. Except you intentionally want to reconnect to the less loaded server.

**Comment by sky01230** [comment] 2019-02-13 07:00
Hi!
"channel.close()" is called in __del__ method in last release and i see "Unclosed connection: Channel..." messages. I wrote finally construction with channel.close() instructuion. Problem still exists.

**Comment by vmagamedov** [comment] 2019-02-14 17:53
I found some cyclic references, going to fix this soon. For now try not to create a channel for every call as I suggested earlier. Or tune GC to collect objects more aggressively.

**Comment by zeyadsalloum** [comment] 2019-03-19 11:18
Hi, I am seeing the same issue and I was wondering if there's any movement on that or If i can help in any way

**Comment by vmagamedov** [comment] 2019-03-19 12:55
I started to analyze references in the "memleaks" branch, but currently I'm working on other features/tasks. I assumed that this issue is not critical, maybe I'm wrong. But nevertheless I'm going to fix this soon.

You can help me if you want. Setup (simplified):
```
git clone git@github.com:vmagamedov/grpclib.git
git checkout memleaks
pip install -e .
pip install -r requirements.txt
pip install objgraph
brew install graphviz
```
Here is how I generate references graph:
```
PYTHONPATH=. py.test tests/test_memory.py
open ./graph.png
```
You can see that there is an implicit reference from `grpclib.protocol.Connection` to the `grpclib.protocol.H2Protocol`. Maybe you can find other accidental references. The goal is to be able to work with the `gc` turned off.

**Comment by vmagamedov** [comment] 2019-03-29 11:43
Here is what I found during my research. There were some cyclic references, but nothing critical. I removed these references in `grpclib` and in `h2` (monkey patching), added tests to detect such references in the future.

You can try `grpclib==0.2.3rc3` to check if memory usage will be different.

Interesting observation: when you create a `Channel` for every request – memory usage is constant, you literally don't need a garbage collector (if cyclic references also eliminated in all other places); when you use a single `Channel` for every request – memory usage grows slightly due to `h2.connection.H2Connection`, which accumulates some data, but since `h2==3.1.0` it does this in a limited fashion: https://github.com/python-hyper/hyper-h2/issues/1163. I'm was using Python 3.6 and 3.7.

I'm looking forward to submit a PR to the `h2` project, but have to figure out how to do this correctly.

**Comment by vmagamedov** [comment] 2019-03-31 18:36
Closing this issue for now, please reopen if you find that `grpclib` causes memory leak. Please perform some debugging before reopening or provide a reproducible example. You can use:
- [objgraph](https://mg.pov.lt/objgraph/) to debug current memory usage
- [pyrasite](http://pyrasite.com) to inject debugging code into running process, even in production
- [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) to debug cases which looks like memory leaks – huge and frequent memory allocations

Just to be sure, I've modified example, and after 1M of unary-stream requests cancelled by the deadline, memory consumption doesn't changed.

**Closed by vmagamedov** 2019-03-31 18:36 UTC
