### ISSUE TITLE
Potential Race between EventsProcessor.close and EventsProcessor.register.release_stream

### ISSUE THREAD

**Issue by lawrencelomax** [vmagamedov/grpclib#78] opened 2019-06-13 14:21 UTC
Hello,

Firstly thanks for the awesome library. Having a pure-python implementation of grpc is very [important for us](https://github.com/facebook/idb)!

We've been seeing a level of "Connection was closed" errors and believe that we've isolated this to some internal races in the `EventsProcessor` code. Since we were pretty sure that the server was well-formed, we executed an identical request with the `grpcio` library and found that we couldn't reproduce this behaviour.

In here I can see [that there is a streams](https://github.com/vmagamedov/grpclib/blob/master/grpclib/protocol.py#L459) dictionary on `EventsProcessor`. This dictionary [is added to in](https://github.com/vmagamedov/grpclib/blob/master/grpclib/protocol.py#L469) `EventsProcessor.register` and de-registered in a [callback that this method returns](https://github.com/vmagamedov/grpclib/blob/master/grpclib/protocol.py#L473).

If there are any active streams at the time that `EventsProcessor.close` is called, [each of the current streams will be marked with "Connection was closed"](https://github.com/vmagamedov/grpclib/blob/master/grpclib/protocol.py#L483). When profiling this, we noticed that the ordering of `EventsProcessor.close` and `release_stream` could vary. If `close` was called before `release_stream`, we'd see this error propagate.

Not too sure of much of the internals here, but I assume that the reason this exists is that:
- There can be many streams per connection.
- If any streams are "active" when a connection has closed, that should be reported as a fault with the underlying TCP transport.
- When a stream is "ended" it will be removed from the set of active streams and will therefore not error out when a connection is closed
- There may be some variance in timing between the delivery of each of these events.

Thanks!

**Comment by lawrencelomax** [comment] 2019-06-13 14:36
For further information, we just added some stack print-debugging into the library and saw that despite all of the data wired back from the server looking consistent. The behaviour of the grpc client was not

In the correct case, we [get a 200](https://gist.github.com/lawrencelomax/c0df8f552e13ae023d7882aadd718531#file-gistfile1-txt-L7) over the wire and also the [error message that was returned on the server](https://gist.github.com/lawrencelomax/c0df8f552e13ae023d7882aadd718531#file-gistfile1-txt-L5). This is correctly [raised as an Application Error](https://gist.github.com/lawrencelomax/c0df8f552e13ae023d7882aadd718531#file-gistfile1-txt-L42). The [stream is released](https://gist.github.com/lawrencelomax/c0df8f552e13ae023d7882aadd718531#file-gistfile1-txt-L56) and [then closed](https://gist.github.com/lawrencelomax/c0df8f552e13ae023d7882aadd718531#file-gistfile1-txt-L74).

In the failing case, we [get a 200](https://gist.github.com/lawrencelomax/961c4d93ab3f1748570d2fadaea89c53#file-gistfile1-txt-L4) over the wire and [also the error message that was returned on the server](https://gist.github.com/lawrencelomax/961c4d93ab3f1748570d2fadaea89c53#file-gistfile1-txt-L2). Then immediately after we [get a closed connection](https://gist.github.com/lawrencelomax/961c4d93ab3f1748570d2fadaea89c53#file-gistfile1-txt-L14) and this is propogated [up as a connection error](https://gist.github.com/lawrencelomax/961c4d93ab3f1748570d2fadaea89c53#file-gistfile1-txt-L86).

In the correct case, the `close` callback comes from the [asyncio protocol stack as connection_lost](https://gist.github.com/lawrencelomax/c0df8f552e13ae023d7882aadd718531#file-gistfile1-txt-L88). In the incorrect case, the `close` [callback from `data_recieved`](https://gist.github.com/lawrencelomax/961c4d93ab3f1748570d2fadaea89c53#file-gistfile1-txt-L28).

**Comment by zeyadsalloum** [comment] 2019-06-13 15:16
it's probably important to note that we are using version 0.2.5 and talking to a grpc server implemented in c++ using google's grpc lib.

**Comment by vmagamedov** [comment] 2019-06-13 19:48
Thank you for a great explanation.

I don't have an idea of what caused `h2.exceptions.ProtocolError` in `H2Protocol.data_received()` method. So I need you to log that exception (full traceback) in a similar way as I did here: [grpclib/protocol.py#L612](https://github.com/vmagamedov/grpclib/blob/1212257/grpclib/protocol.py#L612). Such kind of error is totally unexpected.

Now I see that `EventsProcessor.close()` method could be smarter to not raise exception for finished but not yet released streams (it's like a false positive). So this is definitely a bug.

And maybe you need to know that there is a known issue with a graceful connection shutdown (`GOAWAY` frame). Currently this feature is not implemented and it is possible to receive `StreamTerminatedError` on the client-side when server exits/restarts.

**Comment by zeyadsalloum** [comment] 2019-06-14 09:31
I added the logging where you suggested and repro'd the bug. here's the output. Hope it helps narrow down the problem

`2019-06-14 10:29:53,091 [ERROR] - asyncio - Unclosed connection: Channel('localhost', 10882, ..., path=None)
2019-06-14 10:29:53,190 [ERROR] - asyncio - Fatal error: protocol.data_received() call failed.
protocol: <grpclib.protocol.H2Protocol object at 0x10a96ba90>
transport: <_SelectorSocketTransport fd=11 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpclib/protocol.py", line 532, in data_received
    events = self.connection.feed(data)
  File "/usr/local/lib/python3.7/site-packages/grpclib/protocol.py", line 169, in feed
    return self._connection.receive_data(data)
  File "/usr/local/lib/python3.7/site-packages/h2/connection.py", line 1463, in receive_data
    events.extend(self._receive_frame(frame))
  File "/usr/local/lib/python3.7/site-packages/h2/connection.py", line 1486, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
  File "/usr/local/lib/python3.7/site-packages/h2/connection.py", line 1759, in _receive_rst_stream_frame
    stream_frames, stream_events = stream.stream_reset(frame)
  File "/usr/local/lib/python3.7/site-packages/h2/stream.py", line 1212, in stream_reset
    events = self.state_machine.process_input(StreamInputs.RECV_RST_STREAM)
  File "/usr/local/lib/python3.7/site-packages/h2/stream.py", line 129, in process_input
    return func(self, previous_state)
  File "/usr/local/lib/python3.7/site-packages/h2/stream.py", line 414, in reset_on_closed_stream
    return self.recv_on_closed_stream(previous_state)
  File "/usr/local/lib/python3.7/site-packages/h2/stream.py", line 336, in recv_on_closed_stream
    raise StreamClosedError(self.stream_id)
h2.exceptions.StreamClosedError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 813, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.7/site-packages/grpclib/protocol.py", line 534, in data_received
    log.debug('Protocol error', exc_info=True)
NameError: name 'log' is not defined
2019-06-14 10:29:53,191 [ERROR] - grpclib.server - Application error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpclib/client.py", line 274, in recv_initial_metadata
    headers = await self._stream.recv_headers()
  File "/usr/local/lib/python3.7/site-packages/grpclib/protocol.py", line 233, in recv_headers
    return await self.__headers__.get()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/queues.py", line 159, in get
    await getter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/idb/common/logging.py", line 84, in _async_wrapper
    value = await function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/idb/grpc/ipc_loader.py", line 203, in _tramp
    await partial_call(stream=stream)
  File "/usr/local/lib/python3.7/site-packages/idb/grpc/ipc_loader.py", line 171, in _default_daemon_imp
    _pipe_to_client(out_stream, stream, started_future),
  File "/usr/local/lib/python3.7/site-packages/idb/grpc/ipc_loader.py", line 160, in _pipe_to_client
    async for message in in_stream:
  File "/usr/local/lib/python3.7/site-packages/grpclib/stream.py", line 40, in __anext__
    message = await self.recv_message()
  File "/usr/local/lib/python3.7/site-packages/grpclib/client.py", line 341, in recv_message
    await self.recv_initial_metadata()
  File "/usr/local/lib/python3.7/site-packages/grpclib/client.py", line 298, in recv_initial_metadata
    .format(content_type))
  File "/usr/local/lib/python3.7/site-packages/grpclib/utils.py", line 53, in __exit__
    raise self._error
grpclib.exceptions.StreamTerminatedError: Connection was closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpclib/server.py", line 336, in request_handler
    await method_func(stream)
  File "/usr/local/lib/python3.7/site-packages/idb/common/logging.py", line 109, in _async_wrapper
    raise self.translate_exception(ex)
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'Connection was closed')`

**Comment by vmagamedov** [comment] 2019-06-14 10:19
I found this error in h2 project issues: https://github.com/python-hyper/hyper-h2/issues/1183, have to figure out best way to fix this, don't want to monkey patch h2 library.

**Comment by vmagamedov** [comment] 2019-06-14 14:37
Submitted PR to the h2 library: https://github.com/python-hyper/hyper-h2/pull/1191

**Comment by zeyadsalloum** [comment] 2019-06-27 13:13
Hey Vladimir! I have pulled your pr and built a version of our code with it. and i'm still getting the "Connection was closed" issue. I have built a small client with the official grpc python lib and I wasn't able to repro any problems with that one. so i'm sure it's either something in our use of grpclib or it's the lib itself still. any ideas on how I to debug this further?

**Comment by vmagamedov** [comment] 2019-06-28 16:03
FYI there was a possibility of getting `StreamTerminatedError` instead of `GRPCError` in case when server sends non-ok `grpc-status` in trailers with subsequent `RST_STREAM` frame - #75, fixed in master.

**Comment by zeyadsalloum** [comment] 2019-07-03 16:36
Thanks for updating us! I believe we encountered that a couple of times. is there going to be a release soon? or is it safe to use master?

**Comment by vmagamedov** [comment] 2019-07-05 14:26
I'm going to issue new release candidate very soon. Normally it is safe to use master, it is stable, but there is a possibility of backward-incompatible changes.

**Comment by vmagamedov** [comment] 2019-07-07 12:55
@lawrencelomax @zeyadsalloum My PR was merged into `h2` master, can you reproduce your errors with `grpclib` and `h2` libraries installed from master branches? Let me know if there is anything else needs to be fixed in order to close this issue.

**Comment by mmike-01** [comment] 2019-10-21 21:16
We saw this issue as well. Using `h2` and `grpclib` master branches the error was handled by `protocol.EventsProcessor.process_connection_terminated`: `Received GOAWAY frame, closing connection; error_code: 0`. I found that monkeypatching `grpclib.stream.send_message` to set the current message on the stream was helpful, that way the message could be logged in `EventsProcessor` whenever an error occurs. 

```python
async def send_message(
    stream: 'Stream',
    codec: 'CodecBase',
    message: _SendType,
    message_type: Type[_SendType],
    *,
    end: bool = False,
) -> None:
    setattr(stream, "_current_message", message)
    ...
```

```python
    def process_connection_terminated(
        self,
        event: ConnectionTerminated,
    ) -> None:
        stream = self.streams.get(event.last_stream_id)
        self.close(
            reason=(
                'Received GOAWAY frame, closing connection; '
                'error_code: {}; error data: {}; last stream: {}; all stream ids: {}, current message: {}'
            ).format(
                event.error_code, event, stream, self.streams.keys(), stream._current_message
            )
        )
```

**Comment by vmagamedov** [comment] 2019-10-22 06:58
@mmike-01 I think that you experiencing another issue.

Currently it is not possible to properly handle `GOAWAY` frame, because h2 library doesn't support this yet: https://github.com/python-hyper/hyper-h2/issues/1181

That's why `grpclib` cancels all current streams (rpc calls) when it receives `GOAWAY` frame, because h2 library don't let you finish them.

**Closed by vmagamedov** 2019-10-22 06:58 UTC
